"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const checkout_1 = require("./checkout");
const checkout_2 = require("./checkout");
const co1 = new checkout_1.Checkout(checkout_2.pricingRules);
co1.scan(checkout_2.products[2]);
co1.scan(checkout_2.products[2]);
co1.scan(checkout_2.products[2]);
co1.scan(checkout_2.products[3]);
console.log(co1.total());
const co2 = new checkout_1.Checkout(checkout_2.pricingRules);
co2.scan(checkout_2.products[2]);
co2.scan(checkout_2.products[0]);
co2.scan(checkout_2.products[0]);
co2.scan(checkout_2.products[2]);
co2.scan(checkout_2.products[0]);
co2.scan(checkout_2.products[0]);
co2.scan(checkout_2.products[0]);
console.log(co2.total());
